### PR TITLE
Added cmd+event handler

### LINKED ISSUE #14: Add command handler
**Is your feature request related to a problem? Please describe.**
Dude the code itself looks super unmanged , add a command handler and event handler

**Describe the solution you'd like**
I'll make a custom command handler and port over every single stuff to it

**Describe alternatives you've considered**
Use of wok command can quick the process but isnt that credible

### PR DESCRIPTION
**Pull request by apoorvcodes**
Feat[Added]:
*Command Handler
*Event Handler

Update:
*Shifted All commands to new handler

### CODE REVIEW

**Comment by apoorvcodes** [comment]
@kavin25

**Comment by kavinvalli** [comment]
@apoorvcodes can you please run prettier on the files you've changed

**Comment by apoorvcodes** [comment]
ill do

**Comment by apoorvcodes** [comment]
@kavinvalli lol i forgot about this anyway linted u can merge

**Comment by kavinvalli** [comment]
@apoorvcodes Had a few issues while running code but fixed them myself. Thanks for the PR. Lgtm now so merging

**Pull request merged**
